version: '2.1'

services:

  shell:
    build:
      context: .
      dockerfile: ./shell/Dockerfile
    image: supply-shell
    container_name: shell-trustion_drug_thang
    volumes:
      - .:/project/sawtooth-supply
    command: |
      bash -c "
        protogen
        tail -f /dev/null"
    networks:
      - vchain_vChain
  supply-tp:
    build:
        context: .
        dockerfile: ./processor/Dockerfile
    image: supply-tp
    container_name: supply-tp-trustion_drug_thang
    volumes:
      - '.:/project/sawtooth-supply'
    depends_on:
      - shell
    command: |
      bash -c "
        sleep 1
        tp -v -C tcp://validator:4004"
    networks:
      - vchain_vChain
  supply-rest-api-trustion_drug_thang:
    build:
      context: .
      dockerfile: ./rest_api/Dockerfile
    image: rest-api
    container_name: supply-rest-api-trustion_drug_thang
    volumes:
      - .:/project/sawtooth-supply
    ports:
      - '8096:8096'
    depends_on:
      - shell
    command: |
      bash -c "
        rest-api \
          -B supply-rest-api-trustion_drug_thang:8096 \
          -C validator:4004\
          --db-host postgres \
          -vv"
    networks:
      - vchain_vChain
networks:
  vchain_vChain:
    external: true

